import { uiComponentDeletions295 } from './slow-test-boundary-deletions.ui-295'

export const testBoundaryDeletions = [
  {
    source: 'src/modules/connectors/connector.runner.budgets-validate-auth.test.ts',
    removedCase: 'anchors catch-up coverage at persisted earliest backfill midnight',
    retainedProof: 'src/modules/connectors/connector.runner.auth-catchup.test.ts',
    retainedCase: 'computes first catch-up coverage from persisted earliest backfill midnight',
    reason: 'The auth-catchup suite already owns the persisted earliest-backfill midnight coverage seam, so the duplicate budgets-suite assertion was redundant.',
  },
  {
    source: 'src/server/local-server.connector-schedules.calendar-dst.test.ts',
    removedCase: 'does not introduce timer, cron, or startup schedule-scan loops in schedule modules',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'coalesces missed daily nominals across a spring-forward gap using IANA local time',
    reason: 'Static no-timer inventory scanning is not a schedule-behavior proof; DST coalescing is retained at the eligibility domain seam.',
  },
  {
    source: 'src/test/electron-sourcing-wiring.test.ts',
    removedCase: 'keeps connector schedule UI free of client timers and schedule domain dispatch/history calls',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'coalesces missed daily nominals across a spring-forward gap using IANA local time',
    reason: 'Client timer absence is not a schedule-domain proof; DST coalescing retains the IANA calendar behavior that mattered.',
  },
  {
    source: 'src/modules/applications/application.runtime.test.ts',
    removedCase: 'creates an empty application service from PGlite by default',
    retainedProof: 'src/runtime/local-valedictorian-client.workspace-domain.test.ts',
    retainedCase: 'starts with an empty application list by default',
    reason: 'The workspace-domain client seam already proves the default empty application list without a dedicated PGlite runtime wrapper suite.',
  },
  {
    source: 'src/server/local-server.http-test-harness.test.ts',
    removedCase: 'provides a temporary database path and seeded real local client',
    retainedProof: 'src/server/local-server.http-test-harness.test.ts',
    retainedCase: 'publishes listener closure to lifecycle supervisors',
    reason: 'Harness bootstrap plumbing is covered by the retained lifecycle ownership proofs rather than a standalone setup assertion.',
  },
  {
    source: 'src/server/local-server.http-test-harness.test.ts',
    removedCase: 'starts a public HTTP boundary with typed workspace overrides',
    retainedProof: 'src/server/local-server.http-test-harness.test.ts',
    retainedCase: 'publishes listener closure to lifecycle supervisors',
    reason: 'Typed override startup is incidental harness wiring; retained listener-closure proofs cover harness lifecycle ownership.',
  },
  {
    source: 'src/settings/app-settings.test.ts',
    removedCase: 'keeps valid theme overrides and drops invalid values',
    retainedProof: 'src/theme/theme-registry.test.ts',
    retainedCase: 'validates six- and eight-digit colors without allowing arbitrary CSS',
    reason: 'Theme override acceptance belongs at the theme-registry validator seam, which already rejects arbitrary CSS values.',
  },
  {
    source: 'src/theme/theme-registry.test.ts',
    removedCase: "expect(contrastRatio('#ffffff', '#000000')).toBe(21)",
    retainedProof: 'src/theme/theme-registry.test.ts',
    retainedCase: 'reports contrast issues for inaccessible custom pairs',
    reason: 'A hardcoded perfect-contrast literal is tautological; the retained inaccessible-pair case proves contrast reporting behavior.',
  },
  {
    source: 'src/modules/profile/profile.composition.test.ts',
    removedCase: 'expect(createJsonProfileService).toEqual(expect.any(Function))',
    retainedProof: 'src/modules/profile/profile.composition.test.ts',
    retainedCase: 'observes external edits, fails closed on invalid JSON, restores, restarts, and keeps profile tables absent',
    reason: 'Export-shape smoke checks add no behavior; the retained merged prepare/dispose/restart composition case proves the composition seam.',
  },
  {
    source: 'src/modules/profile/profile.composition.test.ts',
    removedCase: 'prepares one JSON profile and scoped secret capability before use and disposes it',
    retainedProof: 'src/modules/profile/profile.composition.test.ts',
    retainedCase: 'observes external edits, fails closed on invalid JSON, restores, restarts, and keeps profile tables absent',
    reason: 'Ordinary prepare/dispose assertions now live inside the restart composition case on one workspace owner.',
  },
  {
    source: 'src/App.settings.jobright-readd.http.test.tsx',
    removedCase: 'adds a fresh connector-instance id after remove without resurrecting the retired tombstone',
    retainedProof: 'src/App.settings.connector-instance-applicability.test.tsx',
    retainedCase: 're-enables Add after remove and creates a fresh Jobright without stale already-configured state',
    reason: 'Full-App remove/refresh/re-add UI transition retained on fake connectorsApi; HTTP/PGlite lifecycle stays in loaders.connector-readd-lifecycle.',
  },
  {
    source: 'src/server/local-server.domain-routes.test.ts',
    removedCase: 'exposes write-only workspace secrets without a legacy sensitive profile route',
    retainedProof: 'src/server/local-secret-resolution.http.test.ts',
    retainedCase: 'resolves same-named secrets only within each workspace through the manager',
    reason: 'Write-only secret CRUD and legacy sensitive 404s merged into the existing multi-workspace secret HTTP fixture.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'edits with the current revision, discards drafts, and deletes manual-only schedules',
    retainedProof: 'src/settings/connector-schedule.helpers.test.ts',
    retainedCase: 'maps persisted schedules to drafts and detects only real edits',
    reason: 'Schedule edit/discard matrices moved below App into schedule helpers; App retains navigation and reload wiring.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'keeps a persisted IANA timezone alias selected and saves it unchanged',
    retainedProof: 'src/settings/connector-schedule.helpers.test.ts',
    retainedCase: 'preserves a valid persisted IANA timezone alias',
    reason: 'IANA timezone alias validation moved below App into connector-schedule.helpers.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'saves custom daily and weekly schedules with structured cadence and timezone payloads',
    retainedProof: 'src/settings/connector-schedule.helpers.test.ts',
    retainedCase: 'maps custom daily and weekly drafts to canonical cadence',
    reason: 'Custom daily/weekly cadence mapping moved below App into connector-schedule.helpers.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'validates custom interval bounds and preserves draft after typed server errors',
    retainedProof: 'src/settings/connector-schedule.helpers.test.ts',
    retainedCase: 'validates interval boundaries without rendering React',
    reason: 'Interval bound validation moved below App into connector-schedule.helpers.',
  },
  {
    source: 'src/App.settings.connector-run-deep-links.test.tsx',
    removedCase: 'focuses a supplied connector run only once across polling updates',
    retainedProof: 'src/settings/ConnectorRunsPanel.focus.test.tsx',
    retainedCase: 'does not steal focus again when the focused run refreshes',
    reason: 'One-time focus ownership across refreshed run data retained in ConnectorRunsPanel focus component tests.',
  },
  {
    source: 'src/App.settings.connector-run-deep-links.test.tsx',
    removedCase: 'navigates run-specific actions to Connector Runs and focuses the supplied run',
    retainedProof: 'src/App.settings.connector-run-deep-links.test.tsx',
    retainedCase: 'opens and focuses a supplied run, then clears stale focus through ordinary Runs navigation',
    reason: 'Run-specific navigation and focus wiring consolidated into the retained App deep-link case.',
  },
  {
    source: 'src/App.settings.profile-settings.test.tsx',
    removedCase: 'renders and persists structured profile sections with compact reusable answers and secure values',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'renders and persists structured profile sections with compact reusable answers and secure values',
    reason: 'Structured profile section persistence consolidated into ProfileSettingsPanel; App suite retains navigate/loading only.',
  },
  {
    source: 'src/server/raw-source-ledger.http.test.ts',
    removedCase: 'rejects a declared raw batch body above 128 MiB before accumulation',
    retainedProof: 'src/server/local-server.http.unit.test.ts',
    retainedCase: 'rejects a declared oversized body before parsing',
    reason: 'Declared oversized raw-batch rejection retained in local-server.http.unit before HTTP/PGlite.',
  },
  {
    source: 'src/server/local-server.workspace-routing.test.ts',
    removedCase: 'auto-loads registered workspace data for workspace-scoped domain routes',
    retainedProof: 'src/server/local-server.workspace-routing.test.ts',
    retainedCase: 'auto-loads workspace data and returns 404 for another workspace projection revision',
    reason: 'Auto-load sample applications merged into the cross-workspace projection routing fixture.',
  },
  {
    source: 'src/server/local-server.workspace-routing.test.ts',
    removedCase: 'returns 404 for another workspace projection revision through the workspace manager',
    retainedProof: 'src/server/local-server.workspace-routing.test.ts',
    retainedCase: 'auto-loads workspace data and returns 404 for another workspace projection revision',
    reason: 'Standalone projection-revision 404 case renamed into the combined auto-load and cross-workspace projection routing fixture.',
  },
  {
    source: 'src/modules/sourcing/raw-source.repository.test.ts',
    removedCase: 'rejects exact credential header aliases throughout fixed envelopes',
    retainedProof: 'src/modules/sourcing/raw-source.validation.unit.test.ts',
    retainedCase: 'rejects exact credential header aliases throughout fixed envelopes',
    reason: 'Credential-header alias rejection is pure validateRawSourceBatchInput behavior; the unit seam preserves the five-envelope matrix and secrecy assertion without PGlite.',
  },
  {
    source: 'src/modules/sourcing/raw-source.repository.test.ts',
    removedCase: 'rejects unknown keys on every fixed transport envelope',
    retainedProof: 'src/modules/sourcing/raw-source.validation.unit.test.ts',
    retainedCase: 'rejects unknown keys on every fixed transport envelope',
    reason: 'Unknown-property rejection is pure validateRawSourceBatchInput behavior; the unit seam preserves the five-envelope matrix and status/message semantics without PGlite.',
  },
  {
    source: 'src/App.connectors.schedules.test.helpers.test.tsx',
    removedCase: 'opens Overview after the sidebar defers rendering its nested destination',
    retainedProof: 'src/App.connectors.schedules.test.tsx',
    retainedCase: 'keeps cards manual-only with an unavailable-scheduler explanation and never loads schedules',
    reason: 'The helper suite only exercised synthetic DeferredConnectorSidebar polling; real schedule App mounts own the Overview navigation seam.',
  },
  {
    source: 'src/components/ui/badge.test.tsx',
    removedCase: 'renders the current shadcn badge contract with merged classes',
    obsoleteEvidence: 'Asserted only Badge data-slot/variant and Tailwind class merge with no public user-observable behavior.',
    reason: 'Implementation-coupled shadcn/token contract without accessibility, ownership, or wiring obligations.',
  },
  {
    source: 'src/components/ui/card.test.tsx',
    removedCase: 'composes every exported slot with data-slot contracts and caller-owned semantics',
    obsoleteEvidence: 'Asserted only Card data-slot composition and Tailwind recipe classes without a unique public interaction seam.',
    reason: 'Slot/class matrix is implementation-coupled and not a retained #295 React proof.',
  },
  {
    source: 'src/components/ui/empty.test.tsx',
    removedCase: 'composes every exported slot with semantic title, paragraph description, and public data slots',
    obsoleteEvidence: 'Asserted Empty data-slot composition and styling tokens rather than a product-owned empty-state behavior contract.',
    reason: 'Implementation-coupled Empty slot matrix without retained public user-event ownership.',
  },
  {
    source: 'src/components/ui/empty.test.tsx',
    removedCase: 'keeps the default EmptyMedia variant and forwards HTML attributes',
    obsoleteEvidence: 'Asserted EmptyMedia data-slot/variant defaults and trivial DOM prop forwarding only.',
    reason: 'Third-party/passthrough attribute forwarding is not a retained public behavior proof.',
  },
  {
    source: 'src/components/ui/empty.test.tsx',
    removedCase: 'constrains EmptyHeader to the parent width so title and description can wrap in narrow containers',
    obsoleteEvidence: 'Asserted only EmptyHeader max-width Tailwind sizing classes with no accessibility or ownership seam.',
    reason: 'Layout-token assertion without public user-observable behavior.',
  },
  {
    source: 'src/components/ui/scroll-area.test.tsx',
    removedCase: 'renders a labeled viewport with the shared root and scrollbar slots',
    obsoleteEvidence: 'Asserted ScrollArea data-slot structure and focus-ring classes supplied by the third-party primitive.',
    reason: 'Framework/slot contract without a product-owned scroll interaction proof.',
  },
  {
    source: 'src/components/ui/typography.test.tsx',
    removedCase: 'applies shared recipes for heading hierarchy, muted copy, code, and lists',
    obsoleteEvidence: 'Asserted typography recipe Tailwind class names only, with no component behavior beyond class application.',
    reason: 'Styling-token recipe matrix is implementation-coupled and obsolete as a #295 proof.',
  },
  {
    source: 'src/components/ui/alert.test.tsx',
    removedCase: 'composes an accessible informational alert with icon-aware shadcn slots',
    retainedProof: 'src/components/ui/alert.test.tsx',
    retainedCase: 'composes an accessible informational alert with title and description',
    reason: 'Retained the role=alert title/description seam after stripping data-slot and class assertions.',
  },
  {
    source: 'src/components/ui/alert.test.tsx',
    removedCase: 'retains the app semantic tokens for destructive alerts',
    obsoleteEvidence: 'Asserted only destructive variant border/background/text Tailwind tokens with no additional accessibility behavior.',
    reason: 'Semantic-token styling is not a retained public alert proof.',
  },
  {
    source: 'src/components/ui/item.test.tsx',
    removedCase: 'exposes the root data-slot contract with default variant and size',
    obsoleteEvidence: 'Asserted only Item data-slot/data-variant/data-size attributes with no accessible interaction.',
    reason: 'Implementation-coupled slot/variant contract.',
  },
  {
    source: 'src/components/ui/item.test.tsx',
    removedCase: 'applies outline and muted variants plus the sm size',
    obsoleteEvidence: 'Asserted only variant/size data attributes and Tailwind border/background classes.',
    reason: 'Styling-variant matrix without public asChild link behavior.',
  },
  {
    source: 'src/components/ui/item.test.tsx',
    removedCase: 'composes every exported slot with data-slot contracts',
    obsoleteEvidence: 'Asserted Item slot data-slot composition and class merges without a unique ownership seam.',
    reason: 'Slot matrix is implementation-coupled.',
  },
  {
    source: 'src/components/ui/item.test.tsx',
    removedCase: 'forwards asChild onto the caller element while keeping item contracts',
    retainedProof: 'src/components/ui/item.test.tsx',
    retainedCase: 'forwards asChild so the caller anchor is the accessible link',
    reason: 'Retained asChild accessible link/href/text after stripping class/data-slot/variant assertions.',
  },
  {
    source: 'src/components/ui/progress.test.tsx',
    removedCase: 'exposes a determinate progressbar with shadcn slots and forwarded className',
    retainedProof: 'src/components/ui/progress.test.tsx',
    retainedCase: 'exposes a determinate progressbar value',
    reason: 'Retained aria-valuenow determinate proof after stripping class/data-slot assertions.',
  },
  {
    source: 'src/components/ui/separator.test.tsx',
    removedCase: 'renders a decorative horizontal divider with the shared border token',
    retainedProof: 'src/components/ui/separator.test.tsx',
    retainedCase: 'keeps decorative separators out of the accessibility tree',
    reason: 'Retained decorative a11y absence after stripping data-slot and sizing-class assertions.',
  },
  {
    source: 'src/components/ui/separator.test.tsx',
    removedCase: 'applies vertical orientation sizing through the shared data-orientation contract',
    obsoleteEvidence: 'Asserted only decorative vertical data-orientation and Tailwind sizing classes while remaining absent from the a11y tree.',
    reason: 'Pure sizing-class contract duplicate of decorative absence.',
  },
  {
    source: 'src/components/ui/separator.test.tsx',
    removedCase: 'exposes a semantic separator role when decorative is opted out',
    retainedProof: 'src/components/ui/separator.test.tsx',
    retainedCase: 'exposes role, name, and aria-orientation for non-decorative vertical separators',
    reason: 'Non-decorative role/name coverage is retained by the vertical orientation case.',
  },
  {
    source: 'src/components/ui/separator.test.tsx',
    removedCase: 'sets aria-orientation for semantic vertical separators',
    retainedProof: 'src/components/ui/separator.test.tsx',
    retainedCase: 'exposes role, name, and aria-orientation for non-decorative vertical separators',
    reason: 'Renamed retained case keeps the same vertical non-decorative a11y seam.',
  },
  {
    source: 'src/components/ui/separator.test.tsx',
    removedCase: 'merges layout spacing classes without dropping the shared border contract',
    obsoleteEvidence: 'Asserted only className merge of spacing and border Tailwind tokens.',
    reason: 'Class-merge styling is not a public separator behavior proof.',
  },
  {
    source: 'src/components/ui/skeleton.test.tsx',
    removedCase: 'renders the shadcn skeleton slot with accent pulse styling',
    obsoleteEvidence: 'Asserted only Skeleton data-slot and accent/pulse Tailwind classes.',
    reason: 'Accent-pulse styling token contract without accessibility policy.',
  },
  {
    source: 'src/components/ui/skeleton.test.tsx',
    removedCase: 'forwards DOM props and lets callers override aria-hidden',
    retainedProof: 'src/components/ui/skeleton.test.tsx',
    retainedCase: 'lets callers opt out of decorative aria-hidden',
    reason: 'Retained aria-hidden opt-out after stripping data-slot and unrelated DOM/styling asserts.',
  },
  {
    source: 'src/components/ui/skeleton.test.tsx',
    removedCase: 'merges caller className without dropping the shared skeleton contract',
    obsoleteEvidence: 'Asserted only caller className merge with pulse/accent Tailwind tokens.',
    reason: 'Class-merge styling is not a retained Skeleton public seam.',
  },
  {
    source: 'src/components/ui/spinner.test.tsx',
    removedCase: 'exposes an accessible status with spin classes, reduced-motion opt-out, and prop forwarding',
    retainedProof: 'src/components/ui/spinner.test.tsx',
    retainedCase: 'exposes an accessible status with the default Loading label',
    reason: 'Retained accessible status labeling after stripping animation/size class assertions; caller label lives in a dedicated case.',
  },
  {
    source: 'src/components/ui/table.test.tsx',
    removedCase: 'composes a semantic table with caption, data slots, forwarding, and overflow container',
    retainedProof: 'src/components/ui/table.test.tsx',
    retainedCase: 'composes a semantic table with caption, refs, and a labeled container region',
    reason: 'Retained semantic/ref/region proof after stripping every Tailwind and data-slot assertion.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase:
      "{ status: 'retryable' as const, reason: 'old_retry', retryReason: 'server_failure' as const },\n"
      + "    { status: 'failed' as const, reason: 'old_failure' },\n"
      + "    { status: 'action_required' as const, reason: 'old_action' },\n"
      + "    { status: 'cancelled' as const, reason: 'old_cancel' },\n"
      + "    { status: 'invocation_timeout' as const, reason: 'old_timeout' },",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'returns the newer canonical generation when a stale owner finishes with $status',
    reason:
      'Redundant-proof: stale-owner finish rows for retryable/failed/action_required/cancelled/invocation_timeout asserted identical fencing and canonical-generation outcomes already covered by the retained rate_limited representative in the same matrix.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase:
      "[{ status: 'retryable' as const, reason: 'retry', retryReason: 'server_failure' as const }, 'action_required'],",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'persists explicit $status validation and gates subsequent ordinary admission',
    reason:
      'Redundant-proof: the retryable explicit-validation row mapped to the same action_required scope state already represented by the retained action_required row alongside ready and rate_limited.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase: "[{ status: 'failed' as const, reason: 'failed' }, 'action_required'],",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'persists explicit $status validation and gates subsequent ordinary admission',
    reason:
      'Redundant-proof: the failed explicit-validation row mapped to the same action_required scope state already represented by the retained action_required row.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase: "[{ status: 'cancelled' as const, reason: 'cancel' }, 'action_required'],",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'persists explicit $status validation and gates subsequent ordinary admission',
    reason:
      'Redundant-proof: the cancelled explicit-validation row mapped to the same action_required scope state already represented by the retained action_required row.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase: "[{ status: 'invocation_timeout' as const, reason: 'timeout' }, 'action_required'],",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'persists explicit $status validation and gates subsequent ordinary admission',
    reason:
      'Redundant-proof: the invocation-timeout explicit-validation row mapped to the same action_required scope state already represented by the retained action_required row.',
  },
  {
    source: 'src/modules/source-execution/source-session-executor.test.ts',
    removedCase:
      "{ status: 'cancelled' as const, reason: 'cancel' },\n"
      + "    { status: 'invocation_timeout' as const, reason: 'timeout' },",
    retainedProof: 'src/modules/source-execution/source-session-executor.test.ts',
    retainedCase: 'keeps $status closed to ordinary admission after explicit establishment',
    reason:
      'Redundant-proof: cancelled and invocation_timeout ordinary-admission-closed rows asserted the same closed admission and null refresh-lease behavior already covered by the retained retryable representative.',
  },
  {
    source: 'src/modules/sourcing/sourcing.processor.test.ts',
    removedCase: 'links duplicate official URL findings to the existing application',
    retainedProof: 'src/modules/sourcing/sourcing.repository.test.ts',
    retainedCase: 'marks duplicate findings without creating another application',
    reason:
      'Official-URL duplicate linking is already owned by the sourcing repository duplicate-finding proof; the processor suite retains fingerprint and cross-source duplicate paths.',
  },
  {
    source: 'src/App.sourcing-filters-table.test.tsx',
    removedCase: 'distinguishes employer, third-party, and unresolved sourcing destinations without a Review only badge',
    retainedProof: 'src/modules/sourcing/SourcingPage.test.tsx',
    retainedCase: 'distinguishes employer, third-party, and unresolved destinations without a Review only badge',
    reason:
      'Destination presentation is owned by SourcingPage; the App suite retains destination/usability filter loader wiring.',
  },
  {
    source: 'src/App.sourcing-filters-table.test.tsx',
    removedCase: 'separates promoted and blocked sourcing findings in review',
    retainedProof: 'src/modules/sourcing/SourcingPage.test.tsx',
    retainedCase: 'separates promoted and blocked sourcing findings in review',
    reason:
      'Promoted/blocked presentation is owned by SourcingPage; the App suite retains behavioral filter and modal wiring.',
  },
  {
    source: 'src/App.sourcing-filters-table.test.tsx',
    removedCase: 'keeps compact filter controls visually aligned',
    obsoleteEvidence:
      'Asserted only Search/Show-filters input-group height, rounded-md, and document-order Tailwind layout tokens with no filter behavior.',
    reason: 'Implementation-coupled compact layout class assertions without a public filter ownership seam.',
  },
  {
    source: 'src/App.sourcing-filters-table.test.tsx',
    removedCase: 'places reset in a separate expanded filter action row',
    obsoleteEvidence:
      'Asserted only that Reset filters appears inside a Filter actions group after expanding filters, without reset behavior.',
    reason: 'Layout/grouping presentation without the retained clears-filters-with-reset behavior proof.',
  },
  {
    source: 'src/App.sourcing-filters-table.test.tsx',
    removedCase: 'lets the applications table viewport fill the available page height',
    obsoleteEvidence:
      'Asserted only flex/min-h-0/h-full Tailwind height-fill classes on main/page/viewport ancestors.',
    reason: 'Implementation-coupled layout-height class matrix without user-observable table behavior.',
  },
  {
    source: 'src/App.sourcing-normalization.test.tsx',
    removedCase: 'announces list failures and retries through the same public query',
    retainedProof: 'src/modules/sourcing/RawNormalizationPage.test.tsx',
    retainedCase: 'shows scoped request failure for initial list rejection, not domain empty/not-started',
    reason:
      'Scoped list failure, secrecy, and Retry already live on RawNormalizationPage; the App suite retains navigation and finding-open wiring.',
  },
  {
    source: 'src/App.settings.connector-run-progress-history.test.tsx',
    removedCase: 'renders sanitized connector run history with retry guidance',
    retainedProof: 'src/settings/ConnectorRunsPanel.responsive.test.tsx',
    retainedCase: 'sanitizes authentication-expired run history and shows released credential retry guidance',
    reason:
      'Authentication-expired secrecy and released Jobright credential retry guidance are owned by the ConnectorRunsPanel responsive seam; the App suite retains unique run-progress orchestration proofs.',
  },
  {
    source: 'src/App.settings.connector-run-progress-history.test.tsx',
    removedCase: 'keeps Card composition inside articles while preserving focus and live-region ownership',
    retainedProof: 'src/settings/ConnectorRunsPanel.focus.test.tsx',
    retainedCase: 'keeps polite live-region ownership on the focused active run article',
    reason:
      'Card class/data-slot composition was removed as implementation-coupled; focus and polite live-region ownership for the focused active run article are retained by the ConnectorRunsPanel focus seam.',
  },
  {
    source: 'src/App.settings.compact-navigation.test.tsx',
    removedCase: 'opens the application navigation as a narrow drawer without stacking it above content',
    retainedProof: 'src/App.settings.compact-navigation.test.tsx',
    retainedCase: 'closes the narrow application drawer through its explicit close action',
    reason:
      'Layout/CSS stacking and width-class assertions were removed; explicit Close sidebar drawer open/close behavior remains in the same suite.',
  },
  {
    source: 'src/App.settings.compact-navigation.test.tsx',
    removedCase: 'closes the narrow application drawer after changing views',
    retainedProof: 'src/App.settings.navigation-hierarchy.test.tsx',
    retainedCase: 'keeps nested Connectors navigation usable in collapsed, hover, and narrow drawer modes',
    reason:
      'Drawer auto-close after changing views is retained by the navigation-hierarchy narrow-drawer Connectors seam without CSS stacking assertions.',
  },
  {
    source: 'src/App.settings.compact-navigation.test.tsx',
    removedCase: 'uses the same app chrome shell for the settings view',
    retainedProof: 'src/App.settings.compact-navigation.test.tsx',
    retainedCase: 'opens the full settings page from the compact popover and returns to the app',
    reason:
      'Tailwind justify/layout class coupling was removed; the retained popover-to-settings round-trip keeps semantic App chrome banner title Settings and Back to app ownership.',
  },
  {
    source: 'src/App.settings.compact-navigation.test.tsx',
    removedCase: 'left-anchors the capped settings content column beside the sidebar',
    retainedProof: 'src/App.settings.panel-navigation.test.tsx',
    retainedCase: 'opens settings navigation as the same narrow drawer and closes it after panel changes',
    reason:
      'max-w / mx-auto layout tokens are implementation-coupled; panel-navigation retains the AppShell narrow-drawer settings navigation contract.',
  },
  {
    source: 'src/App.settings.compact-navigation.test.tsx',
    removedCase: 'renders grouped settings navigation and filters the sidebar search',
    retainedProof: 'src/App.settings.compact-navigation.test.tsx',
    retainedCase: 'filters settings navigation through Search settings',
    reason:
      'Grouped label and search input-group layout assertions were removed; functional Search settings filtering remains in the same suite.',
  },
  {
    source: 'src/App.settings.profile-destructive-confirm.test.tsx',
    removedCase: 'removes education only after alert confirmation',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'removes education only after alert confirmation',
    reason:
      'Education removal confirmation belongs on ProfileSettingsPanel; App.settings.profile-settings retains navigation wiring.',
  },
  {
    source: 'src/App.settings.profile-destructive-confirm.test.tsx',
    removedCase: 'removes answers and secure values only after alert confirmation',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'removes answers and secure values only after alert confirmation',
    reason:
      'Answer and secure-value removal confirmation belongs on ProfileSettingsPanel; App.settings.profile-settings retains navigation wiring.',
  },
  {
    source: 'src/App.settings.profile-destructive-confirm.test.tsx',
    removedCase: 'disables profile removal confirm while pending and keeps the alert open on error',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'disables profile removal confirm while pending and keeps the alert open on error',
    reason:
      'Pending/error ownership for removal confirms belongs on ProfileSettingsPanel; App.settings.profile-settings retains navigation wiring.',
  },
  {
    source: 'src/App.settings.profile-destructive-confirm.test.tsx',
    removedCase: 'keeps education removal dialog retryable and preserves the item after a failed update',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'keeps education removal dialog retryable and preserves the item after a failed update',
    reason:
      'Education removal retry/preservation belongs on ProfileSettingsPanel; App.settings.profile-settings retains navigation wiring.',
  },
  {
    source: 'src/App.settings.profile-destructive-confirm.test.tsx',
    removedCase: 'keeps reusable-answer removal dialog retryable and preserves the item after a failed update',
    retainedProof: 'src/modules/profile/ProfileSettingsPanel.test.tsx',
    retainedCase: 'keeps reusable-answer removal dialog retryable and preserves the item after a failed update',
    reason:
      'Reusable-answer removal retry/preservation belongs on ProfileSettingsPanel; App.settings.profile-settings retains navigation wiring.',
  },
  {
    source: 'src/App.settings.show-debug-data.test.tsx',
    removedCase: 'hides sourcing raw diagnostic ids by default and reveals them when enabled',
    retainedProof: 'src/modules/sourcing/SourcingPage.test.tsx',
    retainedCase: 'hides sourcing raw diagnostic ids by default and reveals them when enabled',
    reason:
      'Sourcing raw diagnostic id presentation is owned by SourcingPage; the App suite retains Developer settings Switch and secret-absence wiring.',
  },
  {
    source: 'src/App.settings.show-debug-data.test.tsx',
    removedCase: 'hides connector run advanced diagnostics by default and reveals them when enabled',
    retainedProof: 'src/settings/ConnectorRunSynchronizationDetails.test.tsx',
    retainedCase: 'hides connector run advanced diagnostics by default and reveals them when enabled',
    reason:
      'Connector-run advanced diagnostics presentation is owned by ConnectorRunLifecycleDetails; the App suite retains Developer settings Switch and secret-absence wiring.',
  },
  { source: 'src/components/ui/button.test.tsx', removedCase: 'exposes its shadcn slot, variant, and size contract', obsoleteEvidence: 'Asserted only Button data-slot/data-variant/data-size and Tailwind size/color classes with no accessible interaction.', reason: 'Implementation-coupled shadcn slot/variant/size contract without public behavior.' },
  { source: 'src/components/ui/button.test.tsx', removedCase: 'makes disabled primary actions visually muted instead of a full-strength CTA', retainedProof: 'src/components/ui/button.test.tsx', retainedCase: 'keeps disabled actions out of keyboard focus and prevents activation', reason: 'Disabled visual-token class assertions are implementation-coupled; retained disabled focus/activation covers the public seam.' },
  { source: 'src/components/ui/button.test.tsx', removedCase: "expect(link).toHaveAttribute('data-slot', 'button')", retainedProof: 'src/components/ui/button.test.tsx', retainedCase: 'composes an accessible button-like link with asChild', reason: 'Retained asChild accessible link/href after stripping data-slot/data-variant asserts.' },
  { source: 'src/components/ui/button-group.test.tsx', removedCase: 'exposes its shadcn root slot and group role', retainedProof: 'src/components/ui/button-group.test.tsx', retainedCase: 'exposes an accessible named group for its child actions', reason: 'Retained accessible named group after stripping data-slot assertions.' },
  { source: 'src/components/ui/button-group.test.tsx', removedCase: 'merges orientation and className onto the root contract', obsoleteEvidence: 'Asserted only data-orientation and Tailwind flex/className merge tokens with no interaction proof.', reason: 'Orientation/class merge is implementation-coupled styling, not a retained public seam.' },
  { source: 'src/components/ui/sidebar.test.tsx', removedCase: 'exposes structural data-slots and forwards aside props', obsoleteEvidence: 'Asserted only Sidebar structural data-slot composition, className forwarding, and test-id wiring.', reason: 'Framework/slot matrix without accessible interaction or ownership proof.' },
  { source: 'src/components/ui/sidebar.test.tsx', removedCase: 'marks active menu buttons and supports asChild composition', retainedProof: 'src/components/ui/sidebar.test.tsx', retainedCase: 'exposes labeled complementary navigation with asChild accessible links', reason: 'Dropped data-active/active-state claims; retained labeled complementary nav and asChild link/href only.' },
  { source: 'src/components/ui/sidebar.test.tsx', removedCase: "toHaveAttribute('data-active'", obsoleteEvidence: 'Asserted SidebarMenuButton data-active with no distinct accessibility contract.', reason: 'data-active is an implementation attribute, not a retained Sidebar public proof.' },
  { source: 'src/components/ui/sidebar.test.tsx', removedCase: "expect(actionQueue).toHaveClass('focus-visible:ring-ring/50')", retainedProof: 'src/components/ui/sidebar.test.tsx', retainedCase: 'handles click activation, keyboard focus, and disabled semantics', reason: 'Retained click/focus/disabled after stripping focus-ring/opacity class asserts.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'exposes root, input, addon, and text slot/role/class contracts', retainedProof: 'src/components/ui/input-group.test.tsx', retainedCase: 'exposes a named root group with an accessible control', reason: 'Retained named root group query after stripping data-slot/class contracts.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'exposes a group with an accessible named control', retainedProof: 'src/components/ui/input-group.test.tsx', retainedCase: 'exposes a named root group with an accessible control', reason: 'Root must be named so nested addon groups cannot satisfy the query.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'propagates child aria-invalid into the parent error-state class contract', obsoleteEvidence: 'Parent visual-class contract removed; remaining aria-invalid was plain input prop forwarding.', reason: 'aria-invalid pass-through is not an InputGroup-owned proof.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'keeps aria-invalid on the grouped control', obsoleteEvidence: 'Asserted only InputGroupInput aria-invalid attribute forwarding.', reason: 'Plain input prop forwarding is not a retained InputGroup public seam.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'merges caller classes on the root and control without dropping shared contracts', obsoleteEvidence: 'Asserted only className merge of caller and shared InputGroup Tailwind tokens.', reason: 'Class-merge styling is not a retained InputGroup public behavior proof.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: 'keeps disabled controls out of keyboard focus', obsoleteEvidence: 'data-disabled fixture plus native disabled input; proved browser focus skip, not InputGroup ownership.', reason: 'Native disabled focus behavior is not an InputGroup-owned proof.' },
  { source: 'src/components/ui/input-group.test.tsx', removedCase: "expect(textarea).toHaveClass('resize-none', 'bg-transparent')", retainedProof: 'src/components/ui/input-group.test.tsx', retainedCase: 'composes InputGroupTextarea with a block-end addon that focuses the textarea', reason: 'Retained textarea addon-focus ownership after stripping resize/slot/class asserts.' },
  {
    source: 'src/modules/action-queue/action-queue.repository.test.ts',
    removedCase: 'reads the same action queue across on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/applications/application.fixtures.test.ts',
    removedCase: 'keeps fixture rows visible after an on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/connectors/connector-schedule.repository.pglite.test.ts',
    removedCase: 'keeps schedules and revision history visible after an on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/policy/policy.repository.test.ts',
    removedCase: 'persists policy config across on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/sourcing/canonical-candidate.projection.test.ts',
    removedCase: 'keeps a projected finding visible after an on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/sourcing/sourcing.repository.test.ts',
    removedCase: 'keeps findings visible after an on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },
  {
    source: 'src/modules/workflow-runs/workflow-run.repository.test.ts',
    removedCase: 'persists runs across on-disk close and reopen',
    retainedProof: 'src/test/pglite-cross-repository-reopen.smoke.test.ts',
    retainedCase: 'keeps action-queue, application fixtures, schedule revision, policy, canonical projection, sourcing finding, and workflow run visible after one close and reopen',
    reason: 'Generic per-repository close/reopen proofs consolidated into one cross-repository PGlite smoke that seeds and verifies each domain after a single close/reopen.',
  },

  {
    source: 'src/App.settings.jobright-execution.test.tsx',
    removedCase: 'runs an authenticated Jobright connector from settings',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-execution.test.tsx',
    retainedCase: 'shows two persisted non-terminal progress snapshots before terminal connector counts',
    reason: 'Authenticated Run Jobright trigger assertion merged into the progress/terminal execution case on ConnectorSettingsPanel.',
  },
  {
    source: 'src/App.settings-mutation-failure.test.tsx',
    removedCase: 'keeps API token FormFailureAlert when an unrelated ordinary edit starts before the token rejects',
    retainedProof: 'src/app/settings-mutation.test.ts',
    retainedCase: 'keeps an independent key rejection owned after an unrelated newer patch starts',
    reason: 'Cross-key race ownership is proven at the settings-mutation unit seam; App retains representative toast/form ownership.',
  },
  {
    source: 'src/App.settings-mutation-failure.test.tsx',
    removedCase: 'ignores an older rejected settlement so it cannot overwrite a newer successful edit',
    retainedProof: 'src/app/settings-mutation.test.ts',
    retainedCase: 'ignores a superseded same-key rejection while keeping a newer same-key failure owned',
    reason: 'Same-key supersession races are proven at the settings-mutation unit seam.',
  },
  {
    source: 'src/App.settings-mutation-failure.test.tsx',
    removedCase: 'rolls new-target theme rejection back to baseline after an old-target settlement',
    retainedProof: 'src/app/settings-mutation.test.ts',
    retainedCase: 'ignores old-target finalizers after replacement so new rejection rolls back to the real baseline',
    reason: 'API-target replacement races are proven at the settings-mutation unit seam.',
  },
  {
    source: 'src/App.settings-mutation-failure.test.tsx',
    removedCase: 'ignores deferred rejection after unmount and still owns one toast on the next mount',
    retainedProof: 'src/app/settings-mutation.test.ts',
    retainedCase: 'swallows a deferred rejection after lifetime invalidation without updating state',
    reason: 'Unmount lifetime invalidation is proven at the settings-mutation unit seam; App retains representative rollback/toast ownership.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'disables schedule removal confirm while pending and keeps the alert open on error',
    retainedProof: 'src/settings/ConnectorScheduleControls.form-failure.test.tsx',
    retainedCase: 'owns rejected Manual-only confirmation with pending disabled controls and one focused FormFailureAlert',
    reason: 'Pending/error Manual-only removal ownership moved to ConnectorScheduleControls form-failure seam.',
  },
  {
    source: 'src/App.settings.policy-settings.test.tsx',
    removedCase: 'resets policy defaults only after alert confirmation and clears pending section saves',
    retainedProof: 'src/settings/PolicySettingsPanel.mutation-ownership.test.tsx',
    retainedCase: 'resets policy defaults only after alert confirmation and clears pending section saves',
    reason: 'Policy reset confirmation ownership moved to PolicySettingsPanel; App retains successful multi-section save seam.',
  },
  {
    source: 'src/App.settings.policy-settings.test.tsx',
    removedCase: 'keeps the policy reset alert open with an error and disables confirm while pending',
    retainedProof: 'src/settings/PolicySettingsPanel.mutation-ownership.test.tsx',
    retainedCase: 'keeps the policy reset alert open with an error and disables confirm while pending',
    reason: 'Policy reset pending/error ownership moved to PolicySettingsPanel.',
  },
  {
    source: 'src/App.settings.policy-settings.test.tsx',
    removedCase: 'owns policy save failures with one form surface and never duplicates a toast',
    retainedProof: 'src/settings/PolicySettingsPanel.mutation-ownership.test.tsx',
    retainedCase: 'owns policy save failures with one form surface and never duplicates a toast',
    reason: 'Policy save failure form ownership moved to PolicySettingsPanel.',
  },
  {
    source: 'src/App.query-identity-boundary.test.tsx',
    removedCase: 'does not invoke injected loaders when a deferred connector run settles after full App unmount',
    retainedProof: 'src/settings/ConnectorSettingsPanel.mutation-ownership.test.tsx',
    retainedCase: 'ignores a deferred manual-run settlement after unmount',
    reason: 'Full-App unmount characterization is owned by React/component deferred settlement proofs; App retains live query-identity seams.',
  },
  {
    source: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    removedCase: 'does not let persisted exhausted capture work block unrelated discovery after restart',
    retainedProof: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    retainedCase: 'does not let persisted terminal capture or normalization work block unrelated discovery after restart',
    reason: 'Capture/normalization × exhausted/cancelled restart matrix consolidated into one physical close/reopen.',
  },
  {
    source: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    removedCase: 'does not let persisted cancelled capture work block unrelated discovery after restart',
    retainedProof: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    retainedCase: 'does not let persisted terminal capture or normalization work block unrelated discovery after restart',
    reason: 'Capture/normalization × exhausted/cancelled restart matrix consolidated into one physical close/reopen.',
  },
  {
    source: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    removedCase: 'does not let persisted normalization exhausted work block unrelated discovery after restart',
    retainedProof: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    retainedCase: 'does not let persisted terminal capture or normalization work block unrelated discovery after restart',
    reason: 'Capture/normalization × exhausted/cancelled restart matrix consolidated into one physical close/reopen.',
  },
  {
    source: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    removedCase: 'does not let persisted normalization cancelled work block unrelated discovery after restart',
    retainedProof: 'src/modules/connectors/connector.repository.retry-ledger.test.ts',
    retainedCase: 'does not let persisted terminal capture or normalization work block unrelated discovery after restart',
    reason: 'Capture/normalization × exhausted/cancelled restart matrix consolidated into one physical close/reopen.',
  },
  {
    source: 'src/App.sourcing-normalization.migrated.http.test.tsx',
    removedCase: 'renders facts, lineage, normalization, gate, and projection from a legacy connector record',
    retainedProof: 'src/server/raw-source-projection.http.test.ts',
    retainedCase: 'serves legacy connector facts, normalization, gate, and not-eligible projection over HTTP',
    reason: 'Full App+HTTP+PGlite combination replaced by HTTP persistence plus RawNormalizationDetail/App route proofs.',
  },
  {
    source: 'src/server/local-server.connector-schedules.calendar-dst.test.ts',
    removedCase: 'coalesces missed daily nominals across a spring-forward gap using IANA local time',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'coalesces missed daily nominals across a spring-forward gap using IANA local time',
    reason: 'Daily spring-gap coalescing retained at the eligibility domain seam without HTTP/PGlite.',
  },
  {
    source: 'src/server/local-server.connector-schedules.calendar-dst.test.ts',
    removedCase: 'coalesces missed weekly nominals choosing the earlier fall-back overlap instant',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'coalesces missed weekly nominals choosing the earlier fall-back overlap instant',
    reason: 'Weekly fall-overlap coalescing retained at the eligibility domain seam without HTTP/PGlite.',
  },
  {
    source: 'src/server/local-server.connector-schedules.calendar-dst.test.ts',
    removedCase: 'admits a daily spring-forward gap nominal at the first valid local instant after the gap',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'admits a daily spring-forward gap nominal at the first valid local instant after the gap',
    reason: 'Daily spring-gap next eligibility retained at the eligibility domain seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.calendar-dst.test.ts',
    removedCase: 'admits a weekly fall-back overlap nominal at the earlier repeated local instant',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'admits a weekly fall-back overlap nominal at the earlier repeated local instant',
    reason: 'Weekly fall-overlap next eligibility retained at the eligibility domain seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'admits one due scheduled occurrence with exact run provenance and future eligibility',
    retainedProof: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    retainedCase: 'executes an admitted due run exactly once through the shared connector path to a terminal result',
    reason: 'Nominal due provenance merged into the retained HTTP admitted-due execution path.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'returns the same admitted occurrence for repeated dispatch of the same revision and nominal',
    retainedProof: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    retainedCase: 'executes an admitted due run exactly once through the shared connector path to a terminal result',
    reason: 'Repeated dispatch idempotency asserted inside the retained HTTP admitted-due execution path.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'defers due dispatch when an active connector run exists without consuming the occurrence',
    retainedProof: 'src/modules/connectors/connector-schedule.dispatch.pglite.test.ts',
    retainedCase: 'defers due dispatch when an active connector run exists without consuming the occurrence',
    reason: 'Active-run deferral retained at the PGlite admitConnectorScheduleDue seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'coalesces multiple missed interval nominals into one catch_up admission',
    retainedProof: 'src/modules/connectors/connector-schedule.eligibility.test.ts',
    retainedCase: 'coalesces multiple missed interval nominals into one catch_up admission',
    reason: 'Interval coalescing retained at the eligibility domain seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'advances eligibility without admitting when all missed nominals are outside the catch-up horizon',
    retainedProof: 'src/modules/connectors/connector-schedule.dispatch.pglite.test.ts',
    retainedCase: 'advances eligibility without admitting when all missed nominals are outside the catch-up horizon',
    reason: 'PGlite dispatch proof retains not_due mapping, persisted eligibility advancement, unchanged revision, and zero occurrences/runs.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'returns paused without consuming a due occurrence or advancing eligibility',
    retainedProof: 'src/modules/connectors/connector-schedule.dispatch.pglite.test.ts',
    retainedCase: 'returns paused without consuming a due occurrence or advancing eligibility',
    reason: 'Paused dispatch outcome retained at the PGlite admitConnectorScheduleDue seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'returns connector_disabled without consuming a due occurrence or advancing eligibility',
    retainedProof: 'src/modules/connectors/connector-schedule.dispatch.pglite.test.ts',
    retainedCase: 'returns connector_disabled without consuming a due occurrence or advancing eligibility',
    reason: 'Disabled dispatch outcome retained at the PGlite admitConnectorScheduleDue seam.',
  },
  {
    source: 'src/server/local-server.connector-schedules.dispatch.test.ts',
    removedCase: 'preserves an already active connector run when the schedule is paused',
    retainedProof: 'src/modules/connectors/connector-schedule.dispatch.pglite.test.ts',
    retainedCase: 'preserves an already active connector run when the schedule is paused',
    reason: 'Active-paused preservation retained at the PGlite admitConnectorScheduleDue seam.',
  },
  {
    source: 'src/server/local-server.connector-public-trigger.test.ts',
    removedCase: 'keeps HTTP and IPC disabled-connector failures aligned for the public trigger shape',
    retainedProof: 'src/server/local-server.connector-disabled.test.ts',
    retainedCase: 'rejects local and HTTP manual admission without execution until reenabled',
    reason: 'Disabled-connector HTTP/local rejection retained in connector-disabled; secret/hostile projections owned by sanitized-outcomes.',
  },
  {
    source: 'src/server/local-server.connector-public-trigger.test.ts',
    removedCase: 'keeps a secret-bearing refresh throw out of HTTP responses and diagnostic logging',
    retainedProof: 'src/server/local-server.connector-execution.http.test.ts',
    retainedCase: 'returns a fixed 500 for a nominal unexpected connector execution failure',
    reason: 'Runner sanitized-outcomes closes secret diagnostics; this retained HTTP proof owns fixed 500 serialization and request-error logging.',
  },
  {
    source: 'src/server/local-server.connector-public-trigger.test.ts',
    removedCase: 'projects a secret-bearing refresh throw to a fixed IPC rejection',
    retainedProof: 'src/modules/connectors/connector.runner.sanitized-outcomes.test.ts',
    retainedCase: 'converts a secret-bearing refresh throw into a fixed nominal execution error',
    reason: 'Fixed nominal secret projection retained at the runner sanitized-outcomes seam.',
  },
  {
    source: 'src/server/local-server.connector-public-trigger.test.ts',
    removedCase: 'strips hostile adapter diagnostics across direct runner, HTTP logging, and IPC',
    retainedProof: 'src/server/local-server.connector-execution.http.test.ts',
    retainedCase: 'returns a fixed 500 for a nominal unexpected connector execution failure',
    reason: 'Hostile Proxy sanitization remains in runner sanitized-outcomes; this retained HTTP proof owns fixed 500 serialization and request-error logging.',
  },
  {
    source: 'src/server/local-server.error-boundary.http.test.ts',
    removedCase: 'returns fixed parser and body-limit responses without reflecting request values',
    retainedProof: 'src/server/local-server.http.unit.test.ts',
    retainedCase: 'maps the released replay body limit to the fixed HTTP 413 response',
    reason: 'Released body-limit enforcement and fixed 413 boundary mapping moved below the server fixture; malformed JSON remains over real HTTP.',
  },
  {
    source: 'src/modules/sourcing/normalization.repository.exact-success.test.ts',
    removedCase: 'does not treat exact Jobright destinationUrl %s as successful normalization',
    retainedProof: 'src/modules/sourcing/normalization.repository.exact-success.test.ts',
    retainedCase: 'does not treat exact Jobright destinationUrl non-success statuses as successful normalization',
    reason: 'Seven non-success destinationUrl statuses consolidated into one multi-row resettable case.',
  },
  {
    source: 'src/modules/sourcing/normalization.repository.exact-success.test.ts',
    removedCase: 'treats exact Jobright destinationUrl $destinationStatus after the retry window start as successful normalization',
    retainedProof: 'src/modules/sourcing/normalization.repository.exact-success.test.ts',
    retainedCase: 'treats exact Jobright destinationUrl resolved and locked after the retry window start as successful normalization',
    reason: 'Resolved and locked positive statuses consolidated into one multi-row resettable case.',
  },
  {
    source: 'src/modules/action-queue/action-queue.repository.test.ts',
    removedCase: 'places queued applications at or above the cutoff in the apply-now action bucket',
    retainedProof: 'src/modules/action-queue/action-queue.repository.test.ts',
    retainedCase: 'places queued applications into apply-now and skip-below-cutoff buckets from one seed',
    reason: 'Apply-now and skip-below-cutoff bucket proofs share one resettable seed.',
  },
  {
    source: 'src/modules/action-queue/action-queue.repository.test.ts',
    removedCase: 'places queued applications below the cutoff in the skip-below-cutoff action bucket',
    retainedProof: 'src/modules/action-queue/action-queue.repository.test.ts',
    retainedCase: 'places queued applications into apply-now and skip-below-cutoff buckets from one seed',
    reason: 'Apply-now and skip-below-cutoff bucket proofs share one resettable seed.',
  },
  {
    source: 'src/modules/sourcing/projection-outcome.repository.test.ts',
    removedCase: 'stages one pending outcome idempotently',
    retainedProof: 'src/modules/sourcing/projection-outcome.repository.test.ts',
    retainedCase: 'idempotently stages a pending outcome and then marks it projected with its finding reference',
    reason: 'Idempotent staging and projected transition chained on one resettable owner with unique lineage IDs.',
  },
  {
    source: 'src/modules/sourcing/projection-outcome.repository.test.ts',
    removedCase: 'marks a pending outcome projected with its finding reference',
    retainedProof: 'src/modules/sourcing/projection-outcome.repository.test.ts',
    retainedCase: 'idempotently stages a pending outcome and then marks it projected with its finding reference',
    reason: 'Idempotent staging and projected transition chained on one resettable owner with unique lineage IDs.',
  },
  {
    source: 'src/modules/sourcing/sourcing.repository.test.ts',
    removedCase: 'persists an omitted country as unknown on manual create and read',
    retainedProof: 'src/modules/sourcing/sourcing.repository.test.ts',
    retainedCase: 'persists omitted country defaults and omits absent optional usability on manual create',
    reason: 'Ordinary manual-create default proofs consolidated into one resettable create chain.',
  },
  {
    source: 'src/modules/sourcing/sourcing.repository.test.ts',
    removedCase: 'omits absent optional usability from manually created findings',
    retainedProof: 'src/modules/sourcing/sourcing.repository.test.ts',
    retainedCase: 'persists omitted country defaults and omits absent optional usability on manual create',
    reason: 'Ordinary manual-create default proofs consolidated into one resettable create chain.',
  },
  {
    source: 'src/modules/applications/application.repository.attempts.test.ts',
    removedCase: 'rejects submitted completion with a failed final-review verification receipt',
    retainedProof: 'src/modules/applications/application.repository.attempts.test.ts',
    retainedCase: 'rejects submitted completion without a passed final-review verification receipt',
    reason: 'Missing and failed verification-receipt rejection paths chained on one resettable seed.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'shows a capability-load failure without the unavailable explanation and never loads schedules',
    retainedProof: 'src/settings/ConnectorScheduleControls.form-failure.test.tsx',
    retainedCase: 'shows a capability-load failure without the unavailable explanation and never loads schedules',
    reason: 'Capability-load failure UI and no schedule GET owned by ConnectorScheduleControls with the schedule hook.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'creates and reloads a preset schedule across two complete App mounts',
    retainedProof: 'src/settings/useConnectorInstanceSchedules.test.tsx',
    retainedCase: 'saves a preset schedule and reloads the persisted cadence after instance remount',
    reason: 'Preset save and remount reload owned by useConnectorInstanceSchedules without full App mounts.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'pauses and resumes using returned revisions and shows last schedule outcomes',
    retainedProof: 'src/settings/ConnectorScheduleControls.form-failure.test.tsx',
    retainedCase: 'pauses and resumes using returned revisions and shows last schedule outcomes',
    reason: 'Pause/resume revision wiring and last occurrence/run presentation owned by ConnectorScheduleControls harness.',
  },
  {
    source: 'src/App.connectors.schedules.test.tsx',
    removedCase: 'shows connector-disabled schedule state and never uses schedule dispatch helpers',
    retainedProof: 'src/settings/ConnectorScheduleControls.form-failure.test.tsx',
    retainedCase: 'shows connector-disabled schedule state and never uses schedule dispatch helpers',
    reason: 'Disabled connector schedule copy and UI-only schedule API surface owned by ConnectorScheduleControls.',
  },
  {
    source: 'src/App.settings.jobright-execution.test.tsx',
    removedCase: 'shows two persisted non-terminal progress snapshots before terminal connector counts',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-execution.test.tsx',
    retainedCase: 'shows two persisted non-terminal progress snapshots before terminal connector counts',
    reason: 'Progress polling and terminal lifecycle counts owned by ConnectorSettingsPanel without full App chrome.',
  },
  {
    source: 'src/App.settings.jobright-validation-feedback.test.tsx',
    removedCase: 'shows sanitized secure-storage failure when revalidation returns it',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-credential-secrecy.test.tsx',
    retainedCase: 'shows sanitized secure-storage failure when revalidation returns it',
    reason: 'Secure-storage revalidation failure and cancel ownership moved to credential component owner.',
  },
  {
    source: 'src/App.settings.jobright-validation-feedback.test.tsx',
    removedCase: 'keeps failed validation non-ready and clears credential inputs',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-credential-secrecy.test.tsx',
    retainedCase: 'keeps failed validation non-ready and clears credential inputs',
    reason: 'Rejected credential validation clearing and Run gating owned by credential component owner.',
  },
  {
    source: 'src/App.settings.jobright-public-trigger.http.test.tsx',
    removedCase: 'clears optimistic Starting when the public trigger is rejected before persistence',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-execution.test.tsx',
    retainedCase: 'clears optimistic Starting when the public trigger is rejected before persistence',
    reason: 'Optimistic Starting clear on rejected manual trigger owned by ConnectorSettingsPanel; App retains real HTTP persistence.',
  },
  {
    source: 'src/App.settings.earliest-backfill.test.tsx',
    removedCase: 'shows the persisted date, saves calendar changes, discards drafts, and gates Run',
    retainedProof: 'src/settings/ConnectorSettingsPanel.jobright-configuration.test.tsx',
    retainedCase: 'shows the persisted date, saves calendar changes, discards drafts, and gates Run',
    reason: 'Earliest-backfill calendar save/discard and Run gating owned by ConnectorSettingsPanel.',
  },
  {
    source: 'src/App.settings.show-debug-data.test.tsx',
    removedCase: 'exposes a labeled Developer settings Switch that persists showDebugData',
    retainedProof: 'src/settings/SettingsPage.panels.test.tsx',
    retainedCase: 'exposes a labeled Developer settings Switch that persists showDebugData',
    reason: 'Developer settings Switch persistence owned by SettingsPage; App retains cross-surface secret-absence wiring.',
  },
  {
    source: 'src/App.settings.panel-navigation.test.tsx',
    removedCase: 'keeps settings navigation responsive without squeezing the content column',
    obsoleteEvidence: 'Asserted only Tailwind grid/sidebar sizing class contracts without a unique user-event ownership seam.',
    reason: 'Implementation-coupled layout class matrix; drawer close-after-panel and panel content live on cheaper owners.',
  },
  {
    source: 'src/App.settings.panel-navigation.test.tsx',
    removedCase: 'renders functional settings panels and coming-later sidebar items',
    retainedProof: 'src/settings/SettingsPage.panels.test.tsx',
    retainedCase: 'renders functional settings panels and coming-later sidebar items',
    reason: 'Settings panel content matrix owned by SettingsPage without full App chrome.',
  },
  {
    source: 'src/App.settings.panel-navigation.test.tsx',
    removedCase: 'persists full-page settings changes and marks backend changes for restart',
    retainedProof: 'src/App.settings.panel-navigation.test.tsx',
    retainedCase: 'opens settings navigation as the same narrow drawer and closes it after panel changes',
    reason: 'Backend patch persistence and the resulting restart marker are merged into the retained narrow-drawer AppShell proof.',
  },
  // #295 UI-only completion pass: redundant-proof, framework-only, and implementation-coupled
  // shadcn/token cases removed from src/components/ui after the four non-UI sweeps returned null.
  // Authored in a sibling module to keep this file within the 1000-line policy ceiling.
  ...uiComponentDeletions295,
] as const
