export {
  connectorRefreshWarning,
  connectorRefreshWarningMessages,
  ConnectorExecutionError,
  connectorExecutionErrorCode,
  connectorExecutionErrorMessage,
  sanitizeConnectorRefreshWarnings,
  sanitizeConnectorRefreshStopReason,
  sanitizeConnectorAuthValidationResult,
  sanitizeConnectorBoundaryDate,
  sanitizeConnectorSynchronization,
  sanitizeConnectorSynchronizationOutcome,
  type ConnectorAuthOutcomeReason,
  type ConnectorAuthValidationStatus,
  type SanitizedConnectorAuthValidationResult,
  type ConnectorProviderUrlResolverReason,
  type ConnectorRefreshStopReason,
  type ConnectorRefreshWarning,
  type ConnectorRefreshWarningCode,
  type ConnectorSynchronization,
  type ConnectorSynchronizationCancelledReason,
  type ConnectorSynchronizationFailedReason,
  type ConnectorSynchronizationOutcome,
} from "./connector-outcomes.js"

export {
  parseConnectorDynamicOptionsDeclaration,
  parseConnectorOptionValue,
  type ConnectorDynamicOptionSource,
  type ConnectorDynamicOptionsDeclaration,
  type ConnectorOptionObjectSchema,
  type ConnectorOptionScalar,
  type ConnectorOptionScalarSchema,
  type ConnectorOptionValue,
  type ConnectorOptionValueSchema,
} from "./dynamic-options.js"

export type {
  CreateCaptureInput,
  EvidenceMode,
  FieldResolutionOutcome,
  RetryAdvice,
  SourceExecutionScopeId,
  SourceOperationOutcome,
  TransientRetryReason,
  ConnectorHistoricalBackfillState,
  ConnectorNewestFrontierState,
  ConnectorVersionedRendererSchema,
} from "@sparxie/sdk"
export {
  createCaptureInputSchema,
  installedConnectorDescriptorSchema,
  retryAdviceSchema,
  sourceExecutionScopeIdSchema,
} from "@sparxie/sdk"

export type { JsonPrimitive, JsonValue, JsonObject } from "./json.js"
export {
  canonicalCandidateFields,
  canonicalCompensationIntervals,
  canonicalEmploymentTypes,
  canonicalPostedAtPrecisions,
  resolverCapabilities,
  resolverCostClasses,
  type CanonicalCandidateField,
  type CanonicalCompensation,
  type CanonicalCompensationInterval,
  type CanonicalEmploymentType,
  type CanonicalLocation,
  type CanonicalPostedAt,
  type CanonicalPostedAtPrecision,
  type ResolutionEvidence,
  type ResolverCapability,
  type ResolverCostClass,
  type ResolverDeclaration,
  type SourceAdapterKind,
} from "./normalization-types.js"
export {
  connectorReportedOriginKinds,
  type ConnectorCaptureAdapter,
  type ConnectorCaptureEnvelope,
  type ConnectorCaptureEvidence,
  type ConnectorCaptureInput,
  type ConnectorCaptureIntakeRuntime,
  type ConnectorCaptureOccurrence,
  type ConnectorCaptureProvenance,
  type ConnectorCaptureReceipt,
  type ConnectorCaptureReference,
  type ConnectorCaptureRevision,
  type ConnectorReportedOrigin,
  type ConnectorReportedOriginKind,
} from "./capture.js"

export {
  scheduleRetry,
  type RetryPolicyDependencies,
  type RetryPolicyInput,
} from "./retry-policy.js"

export {
  jobObservationSchemaVersion,
  type JobObservation,
  type JobObservationEvidence,
  type JobObservationLinks,
  type JobObservationResolution,
  type JobObservationResolutionStatus,
} from "./observation.js"

export type {
  ConnectorAuthDeclaration,
  ConnectorAuthEstablish,
  ConnectorAuthEstablishmentResult,
  ConnectorAuthGrant,
  ConnectorAuthGrantStatus,
  ConnectorAuthMode,
  ConnectorAuthReference,
  ConnectorAuthRequirement,
  ConnectorAuthResolveInput,
  ConnectorAuthRuntime,
  ConnectorCancellationRuntime,
  ConnectorDelayInput,
  ConnectorDelayRuntime,
  ConnectorNormalizationInput,
  ConnectorNormalizationRuntime,
  ConnectorOptionRuntime,
  ConnectorProgressCounts,
  ConnectorProgressRuntime,
  ConnectorProgressSnapshot,
  ConnectorProgressStage,
  ConnectorProgressWait,
  ConnectorProviderUrlResolverRuntime,
  ConnectorRuntime,
} from "./runtime-ports.js"

export {
  sanitizeConnectorRefreshStats,
  type ConnectorCheckpointPayload,
  type ConnectorCoverageWindow,
  type ConnectorRefreshResult,
  type ConnectorRefreshStats,
  type ConnectorRefreshStatus,
} from "./refresh-result.js"

export type {
  ConnectorAuthValidationInput,
  ConnectorAuthValidationResult,
  ConnectorCapabilityDeclaration,
  ConnectorCheckpointDeclaration,
  ConnectorDefinition,
  ConnectorObservationDeclaration,
  ConnectorOption,
  ConnectorOptionQueryInput,
  ConnectorOptionQueryResult,
  ConnectorProviderFieldResolver,
  ConnectorProviderFieldResolverInput,
  ConnectorProviderUrlResolver,
  ConnectorProviderUrlResolverEvidence,
  ConnectorProviderUrlResolverInput,
  ConnectorProviderUrlResolverResult,
  ConnectorRefreshInput,
  ConnectorRefreshMode,
  ConnectorSchemaDeclaration,
  JobConnector,
} from "./connector-definition.js"
